apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-key-vault-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    template:
      type: Opaque
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-password
