apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: daylog-database
  namespace: daylog
  labels:
    app: daylog
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  instances: 3
  storage:
    size: 1Gi
  superuserSecret:
    name: daylog-database-credentials
