apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: daylog-database-credentials
  namespace: daylog
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-key-vault-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: daylog-db-username
    - secretKey: password
      remoteRef:
        key: daylog-db-password
