apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daylog-pgadmin-data
  namespace: daylog
  labels:
    app: daylog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
