apiVersion: v1
kind: Service
metadata:
  name: daylog-pgadmin
  namespace: daylog
  labels:
    app: daylog
spec:
  type: ClusterIP
  selector:
    app: daylog-pgadmin
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
