apiVersion: batch/v1
kind: CronJob
metadata:
  name: daylog-garmin-sync
  namespace: daylog
  labels:
    app: daylog
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: daylog-automation
          containers:
            - name: daylog-garmin-sync
              image: ghcr.io/patrykanz/daylog:latest
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - python -m backend.api.garmin
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
              env:
                - name: KEY_VAULT_NAME
                  valueFrom:
                    secretKeyRef:
                      name: azure-config
                      key: key-vault-name
                - name: DB_HOST
                  value: daylog-database-rw.daylog.svc.cluster.local
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: azure-creds
                      key: ClientID
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: azure-creds
                      key: ClientSecret
                - name: AZURE_TENANT_ID
                  valueFrom:
                    secretKeyRef:
                      name: azure-config
                      key: tenant-id
          restartPolicy: OnFailure
