apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-creds
  namespace: daylog
  labels:
    app: daylog
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-key-vault-store
    kind: ClusterSecretStore
  target:
    name: azure-creds
    template:
      type: Opaque
  data:
    - secretKey: ClientID
      remoteRef:
        key: azure-client-id
    - secretKey: ClientSecret
      remoteRef:
        key: azure-client-secret
