apiVersion: batch/v1
kind: Job
metadata:
  name: daylog-withings-sync-annual
  namespace: daylog
  labels:
    app: daylog
spec:
  template:
    spec:
      serviceAccountName: daylog-automation
      containers:
        - name: daylog-withings-sync
          image: ghcr.io/patrykanz/daylog:latest
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - python -m backend.api.withings
          env:
            - name: KEY_VAULT_NAME
              valueFrom:
                secretKeyRef:
                  name: azure-config
                  key: key-vault-name
            - name: DB_HOST
              value: daylog-database-rw.daylog.svc.cluster.local
            - name: SYNC_MODE
              value: "year"
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-creds
                  key: ClientID
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-creds
                  key: ClientSecret
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-config
                  key: tenant-id
      restartPolicy: Never
  backoffLimit: 2
